# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2ab8bbaca952af6bc05288ce06c029646b094022e56826cbd8b12576a61d8c3b9c3dd8facdd978a3509237b9c12c2b9d533f9711409c2bc706aa274c28ee4e2

test:
  secret_key_base: 6bc2a3017c0e4f6a9200c8b66ab03ea376ed08f5be86d7ba62f40452d65db821f7eadbf62344e5aa324fc2c2ebf6708d09fc1036cb0a23aece484800410aa75f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
